### ISSUE TITLE
Test PrimitivIOTest/testNonReferenceSerialization1() fails after merging develop branch into minnn

### ISSUE THREAD

**Issue by Alexander230** [milaboratory/milib#72]
java.lang.AssertionError: 
Expected :40
Actual   :60

	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at com.milaboratory.primitivio.PrimitivIOTest.testNonReferenceSerialization1(PrimitivIOTest.java:239)

**Comment by dbolotin** [comment]
On it.

**Comment by dbolotin** [comment]
Thanks! Fixed in develop.
